spring:
  application:
     name: rss-service
  mvc:
    async:
      request-timeout: 5000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rss

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port

jwt:
  secretKey: RHNuM2dNWWF6aDVhNkM0M2E1eG84ejcz
